// Class: ReadMLPBNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBNN
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.27/06       [334598]
Creator        : yeng-mingtzeng
Date           : Mon Sep 15 15:08:35 2014
Host           : Darwin macphsft02.cern.ch 10.4.0 Darwin Kernel Version 10.4.0: Fri Apr 23 18:28:53 PDT 2010; root:xnu-1504.7.4~1/RELEASE_I386 i386
Dir            : /Volumes/Data_HD/panda/files_IBM/ubuntu/CMS/WORKSPACE/stock/STOCK/v_31122009/ana/TMVA/TMVA-v4.2.0/test
Training events: 7921
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
CHF                           CHF                           CHF                           CHF                           units                             'D'    [0.00267950212583,0.960675001144]
NHF                           NHF                           NHF                           NHF                           units                             'D'    [0.00206270441413,0.893177390099]
CHFandNHF                     CHFandNHF                     CHFandNHF                     CHFandNHF                     units                             'D'    [0.0114743113518,0.999999940395]
CHForder                      CHForder                      CHForder                      CHForder                      units                             'I'    [0,14]
NHForder                      NHForder                      NHForder                      NHForder                      units                             'I'    [0,14]
CHFandNHForder                CHFandNHForder                CHFandNHForder                CHFandNHForder                units                             'I'    [0,14]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBNN : public IClassifierReader {

 public:

   // constructor
   ReadMLPBNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBNN" ),
        fNvars( 6 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "CHF", "NHF", "CHFandNHF", "CHForder", "NHForder", "CHFandNHForder" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'I';
      fType[4] = 'I';
      fType[5] = 'I';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][6];
   double fMax_1[3][6];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[12][7];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][12];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBNN::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 7; fWeights[0] = new double[7]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.288930787198011;
   fWeightMatrix0to1[1][0] = 1.21331721783385;
   fWeightMatrix0to1[2][0] = 0.22383793258562;
   fWeightMatrix0to1[3][0] = 1.0164582136294;
   fWeightMatrix0to1[4][0] = -1.23797443483871;
   fWeightMatrix0to1[5][0] = -0.43446985667407;
   fWeightMatrix0to1[6][0] = -0.119477481303647;
   fWeightMatrix0to1[7][0] = 0.609844859146242;
   fWeightMatrix0to1[8][0] = -1.20933753969722;
   fWeightMatrix0to1[9][0] = -0.575739302660396;
   fWeightMatrix0to1[10][0] = -1.72456549544058;
   fWeightMatrix0to1[0][1] = -0.272096756784928;
   fWeightMatrix0to1[1][1] = -0.532682556541271;
   fWeightMatrix0to1[2][1] = -0.205008541008281;
   fWeightMatrix0to1[3][1] = -0.153471182732758;
   fWeightMatrix0to1[4][1] = 0.738960643969591;
   fWeightMatrix0to1[5][1] = -0.685023119863261;
   fWeightMatrix0to1[6][1] = 0.821153012838681;
   fWeightMatrix0to1[7][1] = 1.42022892696282;
   fWeightMatrix0to1[8][1] = 0.847784719458079;
   fWeightMatrix0to1[9][1] = -0.136671829932113;
   fWeightMatrix0to1[10][1] = -0.213050489116815;
   fWeightMatrix0to1[0][2] = 0.236649231480563;
   fWeightMatrix0to1[1][2] = -0.284163288210516;
   fWeightMatrix0to1[2][2] = -1.17077635916745;
   fWeightMatrix0to1[3][2] = 0.17454078124194;
   fWeightMatrix0to1[4][2] = 1.72712782738463;
   fWeightMatrix0to1[5][2] = -0.83195477276652;
   fWeightMatrix0to1[6][2] = -1.09357571643347;
   fWeightMatrix0to1[7][2] = 0.768934249857188;
   fWeightMatrix0to1[8][2] = 0.660475161131523;
   fWeightMatrix0to1[9][2] = 1.89057004777816;
   fWeightMatrix0to1[10][2] = -1.1402933147933;
   fWeightMatrix0to1[0][3] = 0.300695550786585;
   fWeightMatrix0to1[1][3] = -0.119896915484695;
   fWeightMatrix0to1[2][3] = -0.540504439128376;
   fWeightMatrix0to1[3][3] = -0.865220534731596;
   fWeightMatrix0to1[4][3] = 0.557822226557812;
   fWeightMatrix0to1[5][3] = 0.517465278929826;
   fWeightMatrix0to1[6][3] = 0.386136278747855;
   fWeightMatrix0to1[7][3] = 0.143546098357317;
   fWeightMatrix0to1[8][3] = 0.274995179386618;
   fWeightMatrix0to1[9][3] = 0.0358829107319597;
   fWeightMatrix0to1[10][3] = 0.694603485525892;
   fWeightMatrix0to1[0][4] = -0.196435807363658;
   fWeightMatrix0to1[1][4] = -0.6612141108657;
   fWeightMatrix0to1[2][4] = 0.368774052513628;
   fWeightMatrix0to1[3][4] = -0.346772318602496;
   fWeightMatrix0to1[4][4] = 0.386671602382845;
   fWeightMatrix0to1[5][4] = 0.293006801177527;
   fWeightMatrix0to1[6][4] = 0.694411789097035;
   fWeightMatrix0to1[7][4] = 0.498155405807202;
   fWeightMatrix0to1[8][4] = -0.503079955586157;
   fWeightMatrix0to1[9][4] = 0.599426841639809;
   fWeightMatrix0to1[10][4] = 0.301840823403204;
   fWeightMatrix0to1[0][5] = -0.969743129987629;
   fWeightMatrix0to1[1][5] = -0.327635346510134;
   fWeightMatrix0to1[2][5] = -0.604997280749031;
   fWeightMatrix0to1[3][5] = 1.20382536537861;
   fWeightMatrix0to1[4][5] = 0.423097120493724;
   fWeightMatrix0to1[5][5] = -1.96736572937539;
   fWeightMatrix0to1[6][5] = -0.0763477975312399;
   fWeightMatrix0to1[7][5] = -0.153634259337588;
   fWeightMatrix0to1[8][5] = 0.269852802809731;
   fWeightMatrix0to1[9][5] = 1.48800662649747;
   fWeightMatrix0to1[10][5] = -0.0769185528610619;
   fWeightMatrix0to1[0][6] = -0.157733637205366;
   fWeightMatrix0to1[1][6] = -1.26397567668145;
   fWeightMatrix0to1[2][6] = 0.580461401077848;
   fWeightMatrix0to1[3][6] = -0.172159769991641;
   fWeightMatrix0to1[4][6] = -0.519612034616172;
   fWeightMatrix0to1[5][6] = -1.26893720470899;
   fWeightMatrix0to1[6][6] = 0.701396891793648;
   fWeightMatrix0to1[7][6] = 0.95819222499931;
   fWeightMatrix0to1[8][6] = 1.29773327435198;
   fWeightMatrix0to1[9][6] = 0.178781110809539;
   fWeightMatrix0to1[10][6] = -2.1593585994469;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.20390707836487;
   fWeightMatrix1to2[0][1] = 0.1099985705914;
   fWeightMatrix1to2[0][2] = 0.154090176565757;
   fWeightMatrix1to2[0][3] = -0.133429408675707;
   fWeightMatrix1to2[0][4] = 0.175087415277247;
   fWeightMatrix1to2[0][5] = 0.219812418951255;
   fWeightMatrix1to2[0][6] = -0.251687842697433;
   fWeightMatrix1to2[0][7] = -0.238022877467982;
   fWeightMatrix1to2[0][8] = -0.060897127050401;
   fWeightMatrix1to2[0][9] = 0.119462655499151;
   fWeightMatrix1to2[0][10] = -0.306010196706367;
   fWeightMatrix1to2[0][11] = 0.0430333912441139;
}

inline double ReadMLPBNN::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBNN::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBNN::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBNN::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLPBNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0263625122607;
   fMax_1[0][0] = 0.952488720417;
   fMin_1[1][0] = 0.00267950212583;
   fMax_1[1][0] = 0.960675001144;
   fMin_1[2][0] = 0.00267950212583;
   fMax_1[2][0] = 0.960675001144;
   fMin_1[0][1] = 0.00206270441413;
   fMax_1[0][1] = 0.594957470894;
   fMin_1[1][1] = 0.00213675317355;
   fMax_1[1][1] = 0.893177390099;
   fMin_1[2][1] = 0.00206270441413;
   fMax_1[2][1] = 0.893177390099;
   fMin_1[0][2] = 0.0832686722279;
   fMax_1[0][2] = 0.978587567806;
   fMin_1[1][2] = 0.0114743113518;
   fMax_1[1][2] = 0.999999940395;
   fMin_1[2][2] = 0.0114743113518;
   fMax_1[2][2] = 0.999999940395;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 12;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 14;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 14;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 11;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 14;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 14;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 12;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 14;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 14;
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 6;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<6;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
