// Class: ReadCutsD
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Cuts::CutsD
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.31/01       [335617]
Creator        : panda
Date           : Mon Feb 20 01:54:02 2012
Host           : Darwin ymtzeng-2.local 9.8.0 Darwin Kernel Version 9.8.0: Wed Jul 15 16:55:01 PDT 2009; root:xnu-1228.15.4~1/RELEASE_I386 i386
Dir            : /Users/panda/files_IBM/ubuntu/CMS/WORKSPACE/ExcitedQuark/CMSSW/CMSSW_4_2_x_Summer11/REDUCE_DATA/TEST/SBTest/TMVA/TMVA-v4.1.2/test
Training events: 11270
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Decorrelate" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
FitMethod: "MC" [Minimisation Method (GA, SA, and MC are the primary methods to be used; the others have been introduced for testing purposes and are depreciated)]
EffMethod: "EffSel" [Selection Method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
CutRangeMin[0]: "-1.000000e+00" [Minimum of allowed cut range (set per variable)]
    CutRangeMin[1]: "-1.000000e+00"
    CutRangeMin[2]: "-1.000000e+00"
    CutRangeMin[3]: "-1.000000e+00"
CutRangeMax[0]: "-1.000000e+00" [Maximum of allowed cut range (set per variable)]
    CutRangeMax[1]: "-1.000000e+00"
    CutRangeMax[2]: "-1.000000e+00"
    CutRangeMax[3]: "-1.000000e+00"
VarProp[0]: "FSmart" [Categorisation of cuts]
    VarProp[1]: "FSmart"
    VarProp[2]: "FSmart"
    VarProp[3]: "FSmart"
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
var1                          var1                          var1                          d#Phi(Lepb+Leptop)                                              'F'    [0,3.14105629921]
var2                          var2                          var2                          d#Phi(WJ1+Hadtop)                                               'F'    [0,3.14055585861]
var3                          var3                          var3                          GluonFromLepSidePt            GeV                               'F'    [0,806.114562988]
var4                          var4                          var4                          GluonFromHadSidePt            GeV                               'F'    [0,909.490478516]
NSpec 2
var1*2                        spec1                         spec1                         Spectator 1                   units                             'F'    [0,6.28211259842]
var1*3                        spec2                         spec2                         Spectator 2                   units                             'F'    [0,9.42316913605]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadCutsD : public IClassifierReader {

 public:

   // constructor
   ReadCutsD( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadCutsD" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var1", "var2", "var3", "var4" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -0.208355292677879;
      fVmax[0] = 4.49235582351685;
      fVmin[1] = -0.361085176467896;
      fVmax[1] = 4.89575147628784;
      fVmin[2] = -1.39681613445282;
      fVmax[2] = 9.16621208190918;
      fVmin[3] = -1.32593894004822;
      fVmax[3] = 9.67246437072754;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadCutsD() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fDecTF_1[3][4][4];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadCutsD"
};
   inline double ReadCutsD::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadCutsD::InitTransform_1()
{
   // Decorrelation transformation, initialisation
   fDecTF_1[0][0][0] = 1.5460505992;
   fDecTF_1[0][0][1] = -0.0405710306538;
   fDecTF_1[0][0][2] = -0.00129290391763;
   fDecTF_1[0][0][3] = 0.000766842391778;
   fDecTF_1[0][1][0] = -0.0405710306538;
   fDecTF_1[0][1][1] = 1.65684118603;
   fDecTF_1[0][1][2] = 0.000952013871383;
   fDecTF_1[0][1][3] = -0.00147326667943;
   fDecTF_1[0][2][0] = -0.00129290391763;
   fDecTF_1[0][2][1] = 0.000952013871383;
   fDecTF_1[0][2][2] = 0.00994340391349;
   fDecTF_1[0][2][3] = -0.00148379996206;
   fDecTF_1[0][3][0] = 0.000766842391778;
   fDecTF_1[0][3][1] = -0.00147326667943;
   fDecTF_1[0][3][2] = -0.00148379996206;
   fDecTF_1[0][3][3] = 0.00901804032276;
   fDecTF_1[1][0][0] = 1.3284425418;
   fDecTF_1[1][0][1] = -0.0558398016709;
   fDecTF_1[1][0][2] = -0.0011643283231;
   fDecTF_1[1][0][3] = 0.00132569202093;
   fDecTF_1[1][1][0] = -0.0558398016709;
   fDecTF_1[1][1][1] = 1.38694090695;
   fDecTF_1[1][1][2] = 0.00167568871758;
   fDecTF_1[1][1][3] = -0.000935160682987;
   fDecTF_1[1][2][0] = -0.0011643283231;
   fDecTF_1[1][2][1] = 0.00167568871758;
   fDecTF_1[1][2][2] = 0.0168554900188;
   fDecTF_1[1][2][3] = -0.00287645979606;
   fDecTF_1[1][3][0] = 0.00132569202093;
   fDecTF_1[1][3][1] = -0.000935160682987;
   fDecTF_1[1][3][2] = -0.00287645979606;
   fDecTF_1[1][3][3] = 0.0147215872158;
   fDecTF_1[2][0][0] = 1.35404185817;
   fDecTF_1[2][0][1] = -0.0585107037995;
   fDecTF_1[2][0][2] = -0.000800447824101;
   fDecTF_1[2][0][3] = 0.00139844467165;
   fDecTF_1[2][1][0] = -0.0585107037995;
   fDecTF_1[2][1][1] = 1.41765528445;
   fDecTF_1[2][1][2] = 0.00177189483862;
   fDecTF_1[2][1][3] = -0.000774822390074;
   fDecTF_1[2][2][0] = -0.000800447824101;
   fDecTF_1[2][2][1] = 0.00177189483862;
   fDecTF_1[2][2][2] = 0.0136863833027;
   fDecTF_1[2][2][3] = -0.00327452539348;
   fDecTF_1[2][3][0] = 0.00139844467165;
   fDecTF_1[2][3][1] = -0.000774822390074;
   fDecTF_1[2][3][2] = -0.00327452539348;
   fDecTF_1[2][3][3] = 0.0122987027436;
}

//_______________________________________________________________________
inline void ReadCutsD::Transform_1( std::vector<double>& iv, int cls) const
{
   // Decorrelation transformation
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);

   std::vector<double> tv;
   for (int i=0; i<4;i++) {
      double v = 0;
      for (int j=0; j<4; j++)
         v += iv[indicesGet.at(j)] * fDecTF_1[cls][i][j];
      tv.push_back(v);
   }
   for (int i=0; i<4;i++) iv[indicesPut.at(i)] = tv[i];
}

//_______________________________________________________________________
inline void ReadCutsD::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadCutsD::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
